title: Flick
iconURL: assets/default-icon.png
theme: jekyll-theme-midnight

# for a clean URL
permalink: :slug

social:
  twitter: FlickGMD
  github: wdawdjjk

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N 
url: "https://wdawdjjk.github.io"

